modLoader="javafml"
loaderVersion="[45,)"
license="Academic Free License v3.0"

[[mods]]
modId="hanaro_mart"
version="1.19.4 - 1.0"
displayName="HanaroMart"
credits="by pinne"
authors="pinne\n@dev_pinne_"

[[dependencies.hanaro_mart]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4]"
    ordering="NONE"
    side="BOTH"




